# Generated by Django 5.2.1 on 2025-05-15 03:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djsentoo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="currency",
            field=models.CharField(
                choices=[
                    ("ANG", "Netherlands Antillean Guilder"),
                    ("AWG", "Aruban Florin"),
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("XCD", "East Caribbean Dollar"),
                ],
                default="ANG",
                max_length=3,
            ),
        ),
    ]
