# Generated by Django 5.2.1 on 2025-05-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djsentoo", "0002_alter_transaction_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="currency",
            field=models.CharField(
                choices=[
                    ("ANG", "Netherlands Antillean Guilder"),
                    ("AWG", "Aruban Florin"),
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("XCG", "East Caribbean Guilder"),
                ],
                default="XCG",
                max_length=3,
            ),
        ),
    ]
