# Generated by Django 5.2.1 on 2025-05-19 01:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djsentoo", "0003_alter_transaction_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="currency",
            field=models.CharField(
                choices=[
                    ("ANG", "Netherlands Antillean Guilder"),
                    ("AWG", "Aruban Florin"),
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("XCG", "East Caribbean Guilder"),
                ],
                db_index=True,
                default="XCG",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("issued", "Issued"),
                    ("failed", "Failed"),
                    ("pending", "Pending"),
                    ("success", "Success"),
                    ("expired", "Expired"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="issued",
                max_length=20,
            ),
        ),
    ]
